// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using art_galeri.Data;

#nullable disable

namespace art_galeri.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519141007_EtkinlikCokluTarih")]
    partial class EtkinlikCokluTarih
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("art_galeri.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtworkID"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<int>("ArtistID")
                        .HasColumnType("integer");

                    b.Property<int>("BegeniSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("OrtalamaPuan")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YorumSayisi")
                        .HasColumnType("integer");

                    b.HasKey("ArtworkID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("art_galeri.Models.DestekTalebi", b =>
                {
                    b.Property<int>("TalepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TalepID"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("YanitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YoneticiYaniti")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("TalepID");

                    b.HasIndex("UserID");

                    b.ToTable("DestekTalepleri");
                });

            modelBuilder.Entity("art_galeri.Models.EgitmenProfil", b =>
                {
                    b.Property<int>("ProfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfilID"));

                    b.Property<string>("Biyografi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DeneyimYili")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KatilimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SertifikaUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("UzmanlikAlani")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProfilID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("EgitmenProfiller");
                });

            modelBuilder.Entity("art_galeri.Models.Etkinlik", b =>
                {
                    b.Property<int>("EtkinlikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EtkinlikID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<int?>("EgitmenID")
                        .HasColumnType("integer");

                    b.Property<string>("GorselUrl")
                        .HasColumnType("text");

                    b.Property<int>("Kapasite")
                        .HasColumnType("integer");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OrtalamaPuan")
                        .HasColumnType("double precision");

                    b.Property<int>("RezervasyonSayisi")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EtkinlikID");

                    b.HasIndex("EgitmenID");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("art_galeri.Models.EtkinlikTarih", b =>
                {
                    b.Property<int>("EtkinlikTarihID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EtkinlikTarihID"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<int>("EtkinlikID")
                        .HasColumnType("integer");

                    b.Property<int>("Kapasite")
                        .HasColumnType("integer");

                    b.Property<int>("RezervasyonSayisi")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EtkinlikTarihID");

                    b.HasIndex("EtkinlikID");

                    b.ToTable("EtkinlikTarihler");
                });

            modelBuilder.Entity("art_galeri.Models.Favori", b =>
                {
                    b.Property<int>("FavoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriID"));

                    b.Property<int?>("ArtworkID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("FavoriID");

                    b.HasIndex("ArtworkID");

                    b.HasIndex("UserID");

                    b.ToTable("Favoriler");
                });

            modelBuilder.Entity("art_galeri.Models.Kampanya", b =>
                {
                    b.Property<int>("KampanyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KampanyaID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HedefRolID")
                        .HasColumnType("integer");

                    b.Property<decimal>("IndirimOrani")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("KuponKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TargetUserID")
                        .HasColumnType("integer");

                    b.HasKey("KampanyaID");

                    b.HasIndex("HedefRolID");

                    b.HasIndex("KuponKodu")
                        .IsUnique();

                    b.HasIndex("TargetUserID");

                    b.ToTable("Kampanyalar");
                });

            modelBuilder.Entity("art_galeri.Models.Karsilastirma", b =>
                {
                    b.Property<int>("KarsilastirmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KarsilastirmaID"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IDler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("KarsilastirmaID");

                    b.ToTable("Karsilastirmalar");
                });

            modelBuilder.Entity("art_galeri.Models.MusteriProfil", b =>
                {
                    b.Property<int>("ProfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfilID"));

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IlgiAlanlari")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("KatilimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ProfilID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("MusteriProfiller");
                });

            modelBuilder.Entity("art_galeri.Models.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RezervasyonID"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EtkinlikID")
                        .HasColumnType("integer");

                    b.Property<int?>("EtkinlikTarihID")
                        .HasColumnType("integer");

                    b.Property<int>("KatilimciSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RezervasyonTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("RezervasyonID");

                    b.HasIndex("EtkinlikID");

                    b.HasIndex("EtkinlikTarihID");

                    b.HasIndex("UserID");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("art_galeri.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RolID");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            Aciklama = "Eser inceleyen ve satın alan kullanıcılar",
                            RolAdi = "Musteri"
                        },
                        new
                        {
                            RolID = 2,
                            Aciklama = "Sistem yöneticisi - tam yetki",
                            RolAdi = "Yonetici"
                        },
                        new
                        {
                            RolID = 3,
                            Aciklama = "Atölye ve workshop yöneten eğitmenler",
                            RolAdi = "Egitmen"
                        },
                        new
                        {
                            RolID = 4,
                            Aciklama = "Eser yükleyen ve sergileyen sanatçılar",
                            RolAdi = "Sanatci"
                        });
                });

            modelBuilder.Entity("art_galeri.Models.SanatciProfil", b =>
                {
                    b.Property<int>("ProfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfilID"));

                    b.Property<DateTime?>("KatilimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ozgecmis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PortfolyoLinki")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfilFotoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SanatDali")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ProfilID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("SanatciProfiller");
                });

            modelBuilder.Entity("art_galeri.Models.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiparisID"));

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ArtworkID")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("KampanyaID")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("SiparisID");

                    b.HasIndex("ArtworkID");

                    b.HasIndex("KampanyaID");

                    b.HasIndex("UserID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("art_galeri.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RolID")
                        .HasColumnType("integer");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("art_galeri.Models.Yorum", b =>
                {
                    b.Property<int>("YorumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("YorumID"));

                    b.Property<int?>("ArtworkID")
                        .HasColumnType("integer");

                    b.Property<bool>("Dogrulanmis")
                        .HasColumnType("boolean");

                    b.Property<int?>("EtkinlikID")
                        .HasColumnType("integer");

                    b.Property<int>("FaydaliBulma")
                        .HasColumnType("integer");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("boolean");

                    b.Property<int>("Puan")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("YanitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YoneticiYaniti")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("YorumID");

                    b.HasIndex("ArtworkID");

                    b.HasIndex("EtkinlikID");

                    b.HasIndex("UserID");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("art_galeri.Models.Artwork", b =>
                {
                    b.HasOne("art_galeri.Models.User", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("art_galeri.Models.DestekTalebi", b =>
                {
                    b.HasOne("art_galeri.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.EgitmenProfil", b =>
                {
                    b.HasOne("art_galeri.Models.User", "User")
                        .WithOne("EgitmenProfil")
                        .HasForeignKey("art_galeri.Models.EgitmenProfil", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.Etkinlik", b =>
                {
                    b.HasOne("art_galeri.Models.User", "Egitmen")
                        .WithMany()
                        .HasForeignKey("EgitmenID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Egitmen");
                });

            modelBuilder.Entity("art_galeri.Models.EtkinlikTarih", b =>
                {
                    b.HasOne("art_galeri.Models.Etkinlik", "Etkinlik")
                        .WithMany("Tarihler")
                        .HasForeignKey("EtkinlikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etkinlik");
                });

            modelBuilder.Entity("art_galeri.Models.Favori", b =>
                {
                    b.HasOne("art_galeri.Models.Artwork", "Artwork")
                        .WithMany("Favoriler")
                        .HasForeignKey("ArtworkID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("art_galeri.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.Kampanya", b =>
                {
                    b.HasOne("art_galeri.Models.Rol", "HedefRol")
                        .WithMany()
                        .HasForeignKey("HedefRolID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("art_galeri.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserID");

                    b.Navigation("HedefRol");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("art_galeri.Models.MusteriProfil", b =>
                {
                    b.HasOne("art_galeri.Models.User", "User")
                        .WithOne("MusteriProfil")
                        .HasForeignKey("art_galeri.Models.MusteriProfil", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.Rezervasyon", b =>
                {
                    b.HasOne("art_galeri.Models.Etkinlik", "Etkinlik")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("EtkinlikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("art_galeri.Models.EtkinlikTarih", "EtkinlikTarih")
                        .WithMany()
                        .HasForeignKey("EtkinlikTarihID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("art_galeri.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("EtkinlikTarih");

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.SanatciProfil", b =>
                {
                    b.HasOne("art_galeri.Models.User", "User")
                        .WithOne("SanatciProfil")
                        .HasForeignKey("art_galeri.Models.SanatciProfil", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.Siparis", b =>
                {
                    b.HasOne("art_galeri.Models.Artwork", "Artwork")
                        .WithMany("Siparisler")
                        .HasForeignKey("ArtworkID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("art_galeri.Models.Kampanya", "Kampanya")
                        .WithMany()
                        .HasForeignKey("KampanyaID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("art_galeri.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Kampanya");

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.User", b =>
                {
                    b.HasOne("art_galeri.Models.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("art_galeri.Models.Yorum", b =>
                {
                    b.HasOne("art_galeri.Models.Artwork", "Artwork")
                        .WithMany("Yorumlar")
                        .HasForeignKey("ArtworkID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("art_galeri.Models.Etkinlik", "Etkinlik")
                        .WithMany("Yorumlar")
                        .HasForeignKey("EtkinlikID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("art_galeri.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Etkinlik");

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.Artwork", b =>
                {
                    b.Navigation("Favoriler");

                    b.Navigation("Siparisler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("art_galeri.Models.Etkinlik", b =>
                {
                    b.Navigation("Rezervasyonlar");

                    b.Navigation("Tarihler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("art_galeri.Models.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("art_galeri.Models.User", b =>
                {
                    b.Navigation("EgitmenProfil");

                    b.Navigation("MusteriProfil");

                    b.Navigation("SanatciProfil");
                });
#pragma warning restore 612, 618
        }
    }
}
