// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using art_galeri.Data;

#nullable disable

namespace art_galeri.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511192947_RolSistemi")]
    partial class RolSistemi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("art_galeri.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtworkID"));

                    b.Property<int>("ArtistID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArtworkID");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("art_galeri.Models.EgitmenProfil", b =>
                {
                    b.Property<int>("ProfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfilID"));

                    b.Property<string>("Biyografi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DeneyimYili")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KatilimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SertifikaUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("UzmanlikAlani")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProfilID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("EgitmenProfiller");
                });

            modelBuilder.Entity("art_galeri.Models.MusteriProfil", b =>
                {
                    b.Property<int>("ProfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfilID"));

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IlgiAlanlari")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("KatilimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ProfilID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("MusteriProfiller");
                });

            modelBuilder.Entity("art_galeri.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RolID");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            Aciklama = "Eser inceleyen ve satın alan kullanıcılar",
                            RolAdi = "Musteri"
                        },
                        new
                        {
                            RolID = 2,
                            Aciklama = "Sistem yöneticisi - tam yetki",
                            RolAdi = "Yonetici"
                        },
                        new
                        {
                            RolID = 3,
                            Aciklama = "Atölye ve workshop yöneten eğitmenler",
                            RolAdi = "Egitmen"
                        },
                        new
                        {
                            RolID = 4,
                            Aciklama = "Eser yükleyen ve sergileyen sanatçılar",
                            RolAdi = "Sanatci"
                        });
                });

            modelBuilder.Entity("art_galeri.Models.SanatciProfil", b =>
                {
                    b.Property<int>("ProfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfilID"));

                    b.Property<DateTime?>("KatilimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ozgecmis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PortfolyoLinki")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfilFotoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SanatDali")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ProfilID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("SanatciProfiller");
                });

            modelBuilder.Entity("art_galeri.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RolID")
                        .HasColumnType("integer");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("art_galeri.Models.EgitmenProfil", b =>
                {
                    b.HasOne("art_galeri.Models.User", "User")
                        .WithOne("EgitmenProfil")
                        .HasForeignKey("art_galeri.Models.EgitmenProfil", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.MusteriProfil", b =>
                {
                    b.HasOne("art_galeri.Models.User", "User")
                        .WithOne("MusteriProfil")
                        .HasForeignKey("art_galeri.Models.MusteriProfil", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.SanatciProfil", b =>
                {
                    b.HasOne("art_galeri.Models.User", "User")
                        .WithOne("SanatciProfil")
                        .HasForeignKey("art_galeri.Models.SanatciProfil", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("art_galeri.Models.User", b =>
                {
                    b.HasOne("art_galeri.Models.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("art_galeri.Models.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("art_galeri.Models.User", b =>
                {
                    b.Navigation("EgitmenProfil");

                    b.Navigation("MusteriProfil");

                    b.Navigation("SanatciProfil");
                });
#pragma warning restore 612, 618
        }
    }
}
